steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/mylab', '-f', 'Dockerfile.gcp', '.' ]
  # FIXME this is not working. I have to use --timeout 1800s in gcloud CMD
  timeout: 1800s
images:
- 'gcr.io/$PROJECT_ID/mylab'

# gcloud builds submit --config cloudbuild.yaml The $PROJECT_ID will be replaced
# with your default project chosen when you log in via gcloud init
#
# It can be obtained via:
#     gcloud config get-value project


# In my case, it is
# gcr.io/delta-student-285907/mylab

# it can also push to dockerhub:
# https://cloud.google.com/cloud-build/docs/interacting-with-dockerhub-images
