all:
	docker build -t lihebi/mylab-base -f Dockerfile.base .
	docker build -t lihebi/mylab-conda -f Dockerfile.conda .
	docker build -t lihebi/mylab-julia -f Dockerfile.julia .
	docker build -t lihebi/mylab -f Dockerfile.lite .
